"""Add run_type to Game

Revision ID: 3d358b0510ed
Revises: 
Create Date: 2025-08-18 13:13:57.061277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d358b0510ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('run_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('run_type')
        batch_op.drop_column('tags')

    with op.batch_alter_table('community_checklist', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('run_type')

    # ### end Alembic commands ###
